# Generated by Django 2.0.3 on 2018-04-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rammyblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Facebook_url',
            field=models.URLField(default='http://www.facebook.com'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Google',
            field=models.URLField(default='http://www.googleplus.com'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Twitter_url',
            field=models.URLField(default='http://www.twitter.com'),
        ),
    ]
