# Generated by Django 2.0.3 on 2018-04-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rammyblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='comment',
        ),
    ]
